"""
Django settings for safeLife project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%21eprm9=vigr-l=#dwgl7$th66rhzhcqrms2wmz)87jd1*_%9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'imagekit',
    'django_ckeditor_5',
    'django_bootstrap5',
    'articles',
    'main',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'safeLife.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'safeLife.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Обработка статических файлов (CSS, JavaScript, Images)
STATIC_URL = 'static/' # Адрес для статики
STATIC_ROOT = BASE_DIR / 'staticfiles' # Папка сбора статики командой python manage.py collectstatic
STATICFILES_DIRS = [BASE_DIR / 'static', ] # Папка для общих файлов статики

# Медиа файлы (файлы загруженные пользователем)
MEDIA_URL = '/media/' # Адрес для медиа
MEDIA_ROOT = BASE_DIR / 'media' # Папка хранения медиа

# Настройки Ckeditor
CKEDITOR_5_CONFIGS = {
        'default': {
        # Инструменты редактора
        'toolbar': [
                    'undo', 'redo', '|', 'heading', '|',
                    'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough', 'highlight', '|',
                    'insertImage', 'bulletedList', 'numberedList',  'blockQuote', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'insertTable',],
        
        # Настройка возможностей вставки изображений
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        # Настройка возможностей вставки таблицы
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
        },
        # Настройка списка заголовков и шрифтов
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Текст', 'class': 'text' },
                { 'model': 'heading1', 'view': 'h2', 'title': 'Заголовок', 'class': 'title' },
                { 'model': 'heading2', 'view': 'h3', 'title': 'Подзаголовок', 'class': 'sub-title' }
            ]
        }
    }
}

# Путь для загрузки файлов CKEditor 5
DJANGO_CKEDITOR_5_UPLOAD_PATH = "ckeditor/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
