# Generated by Django 5.2.1 on 2025-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Приветствуем вас на сайте!', help_text='Данный текст будет отображаться на главной странице в верхней части', verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Приветствие главной страницы',
            },
        ),
    ]
