# Generated by Django 5.2.1 on 2025-05-29 23:06

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_indexcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': "Страница 'О нас'",
            },
        ),
    ]
