# Generated by Django 5.2.1 on 2025-05-29 23:10

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(default='О нас', verbose_name='Текст страницы'),
        ),
    ]
