# Generated by Django 5.2.1 on 2025-06-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Выбирайте изображения квадтратного формата, иначе аватар может быть некорректно обрезан', null=True, upload_to='users_avatars/', verbose_name='Аватар'),
        ),
    ]
